spring.application.name=portfolio-backend

server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=prnv222@gmail.com
spring.mail.password=gwjm zdjd tnvd myzq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true